// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from '../types';
import type { FloorManifest } from '../types';

const piso5Manifest: FloorManifest = {
  "floorId": "piso5",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-aula-504",
      "label": "AULA 504",
      "aliases": [
        "aula 504",
        "504"
      ],
      "category": "aula",
      "bbox": {
        "x": 1352.726369344417,
        "y": 551.8670571012319,
        "width": 76.6858577989592,
        "height": 152.01359630481363
      },
      "shapeId": "room-aula-504"
    },
    {
      "id": "room-aula-503",
      "label": "AULA 503",
      "aliases": [
        "aula 503",
        "503"
      ],
      "category": "aula",
      "bbox": {
        "x": 499.4133341638592,
        "y": 535.5066316784761,
        "width": 113.179189335719,
        "height": 89.76026397352803
      },
      "shapeId": "room-aula-503"
    },
    {
      "id": "room-aula-500",
      "label": "AULA 500",
      "aliases": [
        "aula 500",
        "500"
      ],
      "category": "aula",
      "bbox": {
        "x": 812.7199991261256,
        "y": 736.6266682282791,
        "width": 178.1158621839346,
        "height": 96.73693059987067
      },
      "shapeId": "room-aula-500"
    },
    {
      "id": "room-aula-509",
      "label": "AULA 509",
      "aliases": [
        "aula 509",
        "509"
      ],
      "category": "aula",
      "bbox": {
        "x": 741.4033370430498,
        "y": 753.8766828081899,
        "width": 67.02586176913326,
        "height": 78.49026558002652
      },
      "shapeId": "room-aula-509"
    },
    {
      "id": "room-aula-507",
      "label": "AULA 507",
      "aliases": [
        "aula 507",
        "507"
      ],
      "category": "aula",
      "bbox": {
        "x": 632.1199967686069,
        "y": 753.6867423734149,
        "width": 109.4225285238208,
        "height": 77.9535966044225
      },
      "shapeId": "room-aula-507"
    },
    {
      "id": "room-aula-505",
      "label": "AULA 505",
      "aliases": [
        "aula 505",
        "505"
      ],
      "category": "aula",
      "bbox": {
        "x": 631.8799823197608,
        "y": 699.936604982926,
        "width": 66.48919074279422,
        "height": 53.803597900025125
      },
      "shapeId": "room-aula-505"
    },
    {
      "id": "room-ing-biomedica",
      "label": "ING. BIOMÉDICA",
      "aliases": [
        "ing. biomedica",
        "ing biomedica"
      ],
      "category": "otro",
      "bbox": {
        "x": 872.2706649002815,
        "y": 656.463455723129,
        "width": 78.42087580177497,
        "height": 47.242629482361735
      },
      "shapeId": "room-ing-biomedica"
    },
    {
      "id": "room-cecom",
      "label": "CECOM",
      "aliases": [
        "cecom"
      ],
      "category": "otro",
      "bbox": {
        "x": 975.475854625183,
        "y": 657.1692827277828,
        "width": 80.56754293330937,
        "height": 47.242629482361735
      },
      "shapeId": "room-cecom"
    },
    {
      "id": "room-aula-510",
      "label": "AULA 510",
      "aliases": [
        "aula 510",
        "510"
      ],
      "category": "aula",
      "bbox": {
        "x": 991.393322843395,
        "y": 735.826747654398,
        "width": 123.37586366637925,
        "height": 97.81026521146646
      },
      "shapeId": "room-aula-510"
    },
    {
      "id": "room-aula-506",
      "label": "AULA 506",
      "aliases": [
        "aula 506",
        "506"
      ],
      "category": "aula",
      "bbox": {
        "x": 1116.006660570562,
        "y": 732.6334106217499,
        "width": 96.00586440760162,
        "height": 99.42026712886036
      },
      "shapeId": "room-aula-506"
    },
    {
      "id": "room-aula-512",
      "label": "AULA 512",
      "aliases": [
        "aula 512",
        "512"
      ],
      "category": "aula",
      "bbox": {
        "x": 1213.390011246141,
        "y": 732.239920833137,
        "width": 44.48586295010023,
        "height": 48.97360133177722
      },
      "shapeId": "room-aula-512"
    },
    {
      "id": "room-departamento-de-quimica",
      "label": "DEPARTAMENTO DE QUÍMICA",
      "aliases": [
        "departamento de quimica"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1261.056649603548,
        "y": 596.673379487397,
        "width": 92.78586492271552,
        "height": 102.10360365784959
      },
      "shapeId": "room-departamento-de-quimica"
    },
    {
      "id": "room-instituto-de-ing-biomedica",
      "label": "INSTITUTO DE ING. BIOMÉDICA",
      "aliases": [
        "instituto de ing. biomedica",
        "instituto de ing biomedica"
      ],
      "category": "instituto",
      "bbox": {
        "x": 1155.0800348596072,
        "y": 455.906644743872,
        "width": 104.05586433223198,
        "height": 79.0269345556303
      },
      "shapeId": "room-instituto-de-ing-biomedica"
    },
    {
      "id": "room-quimica-y-quimica-aplicada",
      "label": "QUÍMICA Y QUÍMICA APLICADA",
      "aliases": [
        "quimica y quimica aplicada"
      ],
      "category": "otro",
      "bbox": {
        "x": 1301.897968685063,
        "y": 409.302275235371,
        "width": 127.13253175277259,
        "height": 142.3536014985117
      },
      "shapeId": "room-quimica-y-quimica-aplicada"
    },
    {
      "id": "room-quimica-de-sistemas-heterogeneos",
      "label": "QUÍMICA DE SISTEMAS HETEROGÉNEOS",
      "aliases": [
        "quimica de sistemas heterogeneos"
      ],
      "category": "otro",
      "bbox": {
        "x": 1301.673356524692,
        "y": 311.12000228973886,
        "width": 128.20587138061887,
        "height": 97.27359790566857
      },
      "shapeId": "room-quimica-de-sistemas-heterogeneos"
    },
    {
      "id": "room-quimica-analitica",
      "label": "QUÍMICA ANALÍTICA",
      "aliases": [
        "quimica analitica"
      ],
      "category": "otro",
      "bbox": {
        "x": 1037.5834084337212,
        "y": 207.84182368130064,
        "width": 129.14106834651648,
        "height": 146.6665601656299
      },
      "shapeId": "room-quimica-analitica"
    },
    {
      "id": "room-quimica-organica",
      "label": "QUÍMICA ORGÁNICA",
      "aliases": [
        "quimica organica"
      ],
      "category": "otro",
      "bbox": {
        "x": 757.4524324004328,
        "y": 173.21144111452736,
        "width": 131.7974326765593,
        "height": 181.935217734518
      },
      "shapeId": "room-quimica-organica"
    },
    {
      "id": "room-aula-501",
      "label": "AULA 501",
      "aliases": [
        "aula 501",
        "501"
      ],
      "category": "aula",
      "bbox": {
        "x": 888.7627818589181,
        "y": 205.06805045826798,
        "width": 74.87533781150069,
        "height": 153.85365574661284
      },
      "shapeId": "room-aula-501"
    },
    {
      "id": "room-aula-502",
      "label": "AULA 502",
      "aliases": [
        "aula 502",
        "502"
      ],
      "category": "aula",
      "bbox": {
        "x": 964.431425184559,
        "y": 234.45864017749193,
        "width": 72.97793367939948,
        "height": 124.56854767367224
      },
      "shapeId": "room-aula-502"
    },
    {
      "id": "room-laboratorio-de-instrumento",
      "label": "LABORATORIO DE INSTRUMENTO",
      "aliases": [
        "laboratorio de instrumento"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 1168.5772058130979,
        "y": 176.99999720106462,
        "width": 115.47975326075766,
        "height": 60.14496762328963
      },
      "shapeId": "room-laboratorio-de-instrumento"
    },
    {
      "id": "room-laboratorio-de-quimica-general-e-inorganica",
      "label": "LABORATORIO DE QUÍMICA GENERAL E INORGÁNICA",
      "aliases": [
        "laboratorio de quimica general e inorganica"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 499.8766467567782,
        "y": 679.280102631914,
        "width": 131.96252491802204,
        "height": 153.62360657123736
      },
      "shapeId": "room-laboratorio-de-quimica-general-e-inorganica"
    },
    {
      "id": "room-fisiloquimica-de-materiales",
      "label": "FISILOQUÍMICA DE MATERIALES",
      "aliases": [
        "fisiloquimica de materiales"
      ],
      "category": "otro",
      "bbox": {
        "x": 645.5183250349604,
        "y": 453.633370828244,
        "width": 124.71751334666237,
        "height": 80.63692812399393
      },
      "shapeId": "room-fisiloquimica-de-materiales"
    },
    {
      "id": "room-bano-damas",
      "label": "BAÑO DAMAS",
      "aliases": [
        "bano damas"
      ],
      "category": "bano",
      "bbox": {
        "x": 769.8145687331343,
        "y": 453.3646990396261,
        "width": 41.231770331512394,
        "height": 80.63692812399393
      },
      "shapeId": "room-bano-damas"
    },
    {
      "id": "room-bano-hombres",
      "label": "BAÑO HOMBRES",
      "aliases": [
        "bano hombres"
      ],
      "category": "bano",
      "bbox": {
        "x": 1118.44128859063,
        "y": 455.4932842636209,
        "width": 34.650384274977114,
        "height": 79.87796538707448
      },
      "shapeId": "room-bano-hombres"
    }
  ]
};

export default piso5Manifest;
