// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from '../types';
import type { FloorManifest } from '../types';

const piso3Manifest: FloorManifest = {
  "floorId": "piso3",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-sec-direccion-biblioteca",
      "label": "SEC. DIRECCIÓN BIBLIOTECA",
      "aliases": [
        "sec. direccion biblioteca",
        "sec direccion biblioteca"
      ],
      "category": "oficina",
      "bbox": {
        "x": 1351.5228,
        "y": 529.073,
        "width": 78.203781,
        "height": 70.804749
      },
      "shapeId": "room-sec-direccion-biblioteca"
    },
    {
      "id": "room-procesos-tecnicos",
      "label": "PROCESOS TÉCNICOS",
      "aliases": [
        "procesos tecnicos"
      ],
      "category": "otro",
      "bbox": {
        "x": 1351.9365,
        "y": 314.20551,
        "width": 77.444817,
        "height": 215.38687
      },
      "shapeId": "room-procesos-tecnicos"
    },
    {
      "id": "room-videoteca",
      "label": "VIDEOTECA",
      "aliases": [
        "videoteca"
      ],
      "category": "otro",
      "bbox": {
        "x": 1170.1743,
        "y": 159.81587,
        "width": 112.35703,
        "height": 78.773842
      },
      "shapeId": "room-videoteca"
    },
    {
      "id": "room-hemeroteca",
      "label": "HEMEROTECA",
      "aliases": [
        "hemeroteca",
        "sala silenciosa",
        "sala parlante"
      ],
      "category": "otro",
      "bbox": {
        "x": 758.65778,
        "y": 158.74417,
        "width": 411.76727,
        "height": 232.84299
      },
      "shapeId": "room-hemeroteca"
    },
    {
      "id": "room-recepcion-biblioteca",
      "label": "RECEPCIÓN BIBLIOTECA",
      "aliases": [
        "recepcion biblioteca"
      ],
      "category": "otro",
      "bbox": {
        "x": 869.05927,
        "y": 389.12601,
        "width": 189.77109,
        "height": 64.353577
      },
      "shapeId": "room-recepcion-biblioteca"
    },
    {
      "id": "room-publicaciones",
      "label": "PUBLICACIONES",
      "aliases": [
        "publicaciones"
      ],
      "category": "otro",
      "bbox": {
        "x": 580.71332,
        "y": 160.50005,
        "width": 179.03775,
        "height": 77.770233
      },
      "shapeId": "room-publicaciones"
    },
    {
      "id": "room-aula-301",
      "label": "AULA 301",
      "aliases": [
        "aula 301",
        "301"
      ],
      "category": "aula",
      "bbox": {
        "x": 647.64337,
        "y": 452.93344,
        "width": 103.90441,
        "height": 79.916901
      },
      "shapeId": "room-aula-301"
    },
    {
      "id": "room-aula-319",
      "label": "AULA 319",
      "aliases": [
        "aula 319",
        "319"
      ],
      "category": "aula",
      "bbox": {
        "x": 873.39331,
        "y": 655.62671,
        "width": 86.194412,
        "height": 74.55024
      },
      "shapeId": "room-aula-319"
    },
    {
      "id": "room-servicio-de-hig-y-seguridad",
      "label": "SERVICIO DE HIG. Y SEGURIDAD",
      "aliases": [
        "servicio de hig. y seguridad",
        "servicio de hig y seguridad"
      ],
      "category": "otro",
      "bbox": {
        "x": 959.39667,
        "y": 655.30145,
        "width": 97.904381,
        "height": 75.177063
      },
      "shapeId": "room-servicio-de-hig-y-seguridad"
    },
    {
      "id": "room-aula-310",
      "label": "AULA 310",
      "aliases": [
        "aula 310",
        "310"
      ],
      "category": "aula",
      "bbox": {
        "x": 1118.4762,
        "y": 702.86395,
        "width": 170.0381,
        "height": 59.040844
      },
      "shapeId": "room-aula-310"
    },
    {
      "id": "room-sec-empresarial",
      "label": "SEC. EMPRESARIAL",
      "aliases": [
        "sec. empresarial",
        "sec empresarial"
      ],
      "category": "oficina",
      "bbox": {
        "x": 1349.7156,
        "y": 767.32758,
        "width": 80.101181,
        "height": 62.835655
      },
      "shapeId": "room-sec-empresarial"
    },
    {
      "id": "room-aula-304",
      "label": "AULA 304",
      "aliases": [
        "aula 304",
        "304"
      ],
      "category": "aula",
      "bbox": {
        "x": 1283.2472,
        "y": 832.98749,
        "width": 65.680916,
        "height": 79.15332
      },
      "shapeId": "room-aula-304"
    },
    {
      "id": "room-aula-302",
      "label": "AULA 302",
      "aliases": [
        "aula 302",
        "302"
      ],
      "category": "aula",
      "bbox": {
        "x": 1351.6377,
        "y": 599.83618,
        "width": 77.824295,
        "height": 164.15698
      },
      "shapeId": "room-aula-302"
    },
    {
      "id": "room-aula-313",
      "label": "AULA 313",
      "aliases": [
        "aula 313",
        "313"
      ],
      "category": "aula",
      "bbox": {
        "x": 642.87,
        "y": 703.00671,
        "width": 164.01108,
        "height": 60.060238
      },
      "shapeId": "room-aula-313"
    },
    {
      "id": "room-aula-305",
      "label": "AULA 305",
      "aliases": [
        "aula 305",
        "305"
      ],
      "category": "aula",
      "bbox": {
        "x": 499.20001,
        "y": 651.24658,
        "width": 80.827744,
        "height": 114.26357
      },
      "shapeId": "room-aula-305"
    },
    {
      "id": "room-aula-303",
      "label": "AULA 303",
      "aliases": [
        "aula 303",
        "303"
      ],
      "category": "aula",
      "bbox": {
        "x": 499.21997,
        "y": 537.20996,
        "width": 80.827744,
        "height": 114.26357
      },
      "shapeId": "room-aula-303"
    },
    {
      "id": "room-bano-damas",
      "label": "BAÑO DAMAS",
      "aliases": [
        "bano damas"
      ],
      "category": "bano",
      "bbox": {
        "x": 752.22668,
        "y": 453.45667,
        "width": 59.897747,
        "height": 77.770233
      },
      "shapeId": "room-bano-damas"
    },
    {
      "id": "room-bano-hombres",
      "label": "BAÑO HOMBRES",
      "aliases": [
        "bano hombres"
      ],
      "category": "bano",
      "bbox": {
        "x": 1117.1801,
        "y": 454.3334,
        "width": 64.191078,
        "height": 77.233574
      },
      "shapeId": "room-bano-hombres"
    },
    {
      "id": "room-dir-de-biblio",
      "label": "DIR. DE BIBLIO",
      "aliases": [
        "dir. de biblio",
        "dir de biblio"
      ],
      "category": "otro",
      "bbox": {
        "x": 1180.9066,
        "y": 456.74994,
        "width": 55.067745,
        "height": 75.086906
      },
      "shapeId": "room-dir-de-biblio"
    }
  ]
};

export default piso3Manifest;
