// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from '../types';
import type { FloorManifest } from '../types';

const piso1Manifest: FloorManifest = {
  "floorId": "piso1",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-aula-l3",
      "label": "AULA L3",
      "aliases": [
        "aula l3"
      ],
      "category": "aula",
      "bbox": {
        "x": 1118.723090126427,
        "y": 703.1272513841,
        "width": 61.83049021062175,
        "height": 128.7361106934154
      },
      "shapeId": "room-aula-l3"
    },
    {
      "id": "room-aula-l2",
      "label": "AULA L2",
      "aliases": [
        "aula l2"
      ],
      "category": "aula",
      "bbox": {
        "x": 1180.7638436695458,
        "y": 765.9517039650539,
        "width": 44.7538607638819,
        "height": 64.98336501303561
      },
      "shapeId": "room-aula-l2"
    },
    {
      "id": "room-aula-l1",
      "label": "AULA L1",
      "aliases": [
        "aula l1"
      ],
      "category": "aula",
      "bbox": {
        "x": 1266.220014443689,
        "y": 768.0049448139089,
        "width": 80.42504061898649,
        "height": 62.32700044656758
      },
      "shapeId": "room-aula-l1"
    },
    {
      "id": "room-aula-l5",
      "label": "AULA L5",
      "aliases": [
        "aula l5"
      ],
      "category": "aula",
      "bbox": {
        "x": 1353.266627667792,
        "y": 697.461661179291,
        "width": 77.47337732101369,
        "height": 30.313944540460398
      },
      "shapeId": "room-aula-l5"
    },
    {
      "id": "room-aula-l6",
      "label": "AULA L6",
      "aliases": [
        "aula l6"
      ],
      "category": "aula",
      "bbox": {
        "x": 1349.9999297247768,
        "y": 642.1866245269059,
        "width": 81.76671075162994,
        "height": 54.46394632627175
      },
      "shapeId": "room-aula-l6"
    },
    {
      "id": "room-labi",
      "label": "LABI",
      "aliases": [
        "labi"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 1264.083300209073,
        "y": 597.123316983829,
        "width": 54.93338016950861,
        "height": 105.9839510494669
      },
      "shapeId": "room-labi"
    },
    {
      "id": "room-aula-l7",
      "label": "AULA L7",
      "aliases": [
        "aula l7"
      ],
      "category": "aula",
      "bbox": {
        "x": 1351.166620649475,
        "y": 591.139938846505,
        "width": 80.15671147860985,
        "height": 51.24394713212337
      },
      "shapeId": "room-aula-l7"
    },
    {
      "id": "room-aula-l9",
      "label": "AULA L9",
      "aliases": [
        "aula l9"
      ],
      "category": "aula",
      "bbox": {
        "x": 1351.150007732947,
        "y": 527.0167152701521,
        "width": 80.15671147860985,
        "height": 64.66061109354916
      },
      "shapeId": "room-aula-l9"
    },
    {
      "id": "room-aula-l10",
      "label": "AULA L10",
      "aliases": [
        "aula l10"
      ],
      "category": "aula",
      "bbox": {
        "x": 1350.90001998534,
        "y": 473.88666397168504,
        "width": 80.69338197474303,
        "height": 53.92728305628839
      },
      "shapeId": "room-aula-l10"
    },
    {
      "id": "room-aula-l11",
      "label": "AULA L11",
      "aliases": [
        "aula l11"
      ],
      "category": "aula",
      "bbox": {
        "x": 1287.134943429653,
        "y": 427.77668218607994,
        "width": 39.16817068887508,
        "height": 106.486224321382
      },
      "shapeId": "room-aula-l11"
    },
    {
      "id": "room-aula-l13",
      "label": "AULA L13",
      "aliases": [
        "aula l13"
      ],
      "category": "aula",
      "bbox": {
        "x": 1183.03749231172,
        "y": 455.852947516483,
        "width": 53.92650489104108,
        "height": 77.50622765919843
      },
      "shapeId": "room-aula-l13"
    },
    {
      "id": "room-bano-hombres",
      "label": "BAÑO HOMBRES",
      "aliases": [
        "bano hombres"
      ],
      "category": "bano",
      "bbox": {
        "x": 1119.3549306465818,
        "y": 455.85337814996103,
        "width": 60.634837841955914,
        "height": 77.50622765919843
      },
      "shapeId": "room-bano-hombres"
    },
    {
      "id": "room-bano-damas",
      "label": "BAÑO DAMAS",
      "aliases": [
        "bano damas"
      ],
      "category": "bano",
      "bbox": {
        "x": 754.254574263898,
        "y": 456.36465753384095,
        "width": 58.29284720364558,
        "height": 78.3763323886219
      },
      "shapeId": "room-bano-damas"
    },
    {
      "id": "room-aula-l14",
      "label": "AULA L14",
      "aliases": [
        "aula l14"
      ],
      "category": "aula",
      "bbox": {
        "x": 1059.770018135354,
        "y": 600.5833395340649,
        "width": 54.99983794331047,
        "height": 130.63351507370658
      },
      "shapeId": "room-aula-l14"
    },
    {
      "id": "room-aula-103",
      "label": "AULA 103",
      "aliases": [
        "aula 103",
        "103"
      ],
      "category": "aula",
      "bbox": {
        "x": 810.615542661411,
        "y": 601.4041660916309,
        "width": 61.70817150499431,
        "height": 130.36518148129016
      },
      "shapeId": "room-aula-103"
    },
    {
      "id": "room-extension-universitaria",
      "label": "EXTENSIÓN UNIVERSITARIA",
      "aliases": [
        "extension universitaria"
      ],
      "category": "otro",
      "bbox": {
        "x": 648.2509131281751,
        "y": 455.6279806727259,
        "width": 104.96896960514368,
        "height": 79.13529257479854
      },
      "shapeId": "room-extension-universitaria"
    },
    {
      "id": "room-laboratorio-de-solidos-amorfos",
      "label": "LABORATORIO DE SÓLIDOS AMORFOS",
      "aliases": [
        "laboratorio de solidos amorfos"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 581.41293563,
        "y": 160.11996729999998,
        "width": 177.44976850965008,
        "height": 79.13529257479854
      },
      "shapeId": "room-laboratorio-de-solidos-amorfos"
    },
    {
      "id": "room-aula-105",
      "label": "AULA 105",
      "aliases": [
        "aula 105",
        "105"
      ],
      "category": "aula",
      "bbox": {
        "x": 609.5537870289954,
        "y": 602.589386868581,
        "width": 53.359598276057795,
        "height": 101.05029878009009
      },
      "shapeId": "room-aula-105"
    },
    {
      "id": "room-aula-107",
      "label": "AULA 107",
      "aliases": [
        "aula 107",
        "107"
      ],
      "category": "aula",
      "bbox": {
        "x": 497.8109129249393,
        "y": 538.3807412695919,
        "width": 84.85648724131158,
        "height": 116.32439454792416
      },
      "shapeId": "room-aula-107"
    },
    {
      "id": "room-laboratorio-de-compu",
      "label": "LABORATORIO DE COMPU",
      "aliases": [
        "laboratorio de compu"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 497.9542848376519,
        "y": 654.8146576555209,
        "width": 84.0975273712678,
        "height": 60.16125855901009
      },
      "shapeId": "room-laboratorio-de-compu"
    },
    {
      "id": "room-departamento-de-matematica",
      "label": "DEPARTAMENTO DE MATEMÁTICA",
      "aliases": [
        "departamento de matematica"
      ],
      "category": "departamento",
      "bbox": {
        "x": 499.03584067283396,
        "y": 713.430137771001,
        "width": 83.33856750122402,
        "height": 57.12541389945363
      },
      "shapeId": "room-departamento-de-matematica"
    },
    {
      "id": "room-depto-de-electronica",
      "label": "DEPTO DE ELECTRÓNICA",
      "aliases": [
        "depto de electronica"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1374.355015046916,
        "y": 770.73964356745,
        "width": 57.08004138789579,
        "height": 60.367279487159976
      },
      "shapeId": "room-depto-de-electronica"
    },
    {
      "id": "room-sala-de-clase-de-consulta",
      "label": "SALA DE CLASE DE CONSULTA",
      "aliases": [
        "sala de clase de consulta"
      ],
      "category": "sala",
      "bbox": {
        "x": 582.2867383932333,
        "y": 768.0913064004969,
        "width": 59.81077121911608,
        "height": 64.00210595324052
      },
      "shapeId": "room-sala-de-clase-de-consulta"
    },
    {
      "id": "room-sala-de-profesores",
      "label": "SALA DE PROFESORES",
      "aliases": [
        "sala de profesores"
      ],
      "category": "sala",
      "bbox": {
        "x": 579.5100237647559,
        "y": 832.0334290251019,
        "width": 65.71410758736602,
        "height": 79.83377616126472
      },
      "shapeId": "room-sala-de-profesores"
    }
  ]
};

export default piso1Manifest;
