// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from '../types';
import type { FloorManifest } from '../types';

const piso2Manifest: FloorManifest = {
  "floorId": "piso2",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-aula-200",
      "label": "AULA 200",
      "aliases": [
        "aula 200",
        "200"
      ],
      "category": "aula",
      "bbox": {
        "x": 810.4067605559912,
        "y": 735.3350022755592,
        "width": 263.8253465965645,
        "height": 96.53698456239886
      },
      "shapeId": "room-aula-200"
    },
    {
      "id": "room-aula-202",
      "label": "AULA 202",
      "aliases": [
        "aula 202",
        "202"
      ],
      "category": "aula",
      "bbox": {
        "x": 1172.9585788964928,
        "y": 703.3066422428304,
        "width": 115.06133803988405,
        "height": 61.65365261827367
      },
      "shapeId": "room-aula-202"
    },
    {
      "id": "room-aula-203",
      "label": "AULA 203",
      "aliases": [
        "aula 203",
        "203"
      ],
      "category": "aula",
      "bbox": {
        "x": 643.619886105997,
        "y": 699.19334808232,
        "width": 165.07867025314908,
        "height": 71.85032130397235
      },
      "shapeId": "room-aula-203"
    },
    {
      "id": "room-aula-201",
      "label": "AULA 201",
      "aliases": [
        "aula 201",
        "201"
      ],
      "category": "aula",
      "bbox": {
        "x": 499.05354560791966,
        "y": 355.3632651711732,
        "width": 145.22202216863252,
        "height": 177.0369859372945
      },
      "shapeId": "room-aula-201"
    },
    {
      "id": "room-aula-237",
      "label": "AULA 237",
      "aliases": [
        "aula 237",
        "237"
      ],
      "category": "aula",
      "bbox": {
        "x": 648.4233444658929,
        "y": 453.5799760374425,
        "width": 74.9186778402709,
        "height": 80.97365413924626
      },
      "shapeId": "room-aula-237"
    },
    {
      "id": "room-aula-221",
      "label": "AULA 221",
      "aliases": [
        "aula 221",
        "221"
      ],
      "category": "aula",
      "bbox": {
        "x": 868.440004406556,
        "y": 396.8433872584567,
        "width": 95.84867742795882,
        "height": 116.93032368526383
      },
      "shapeId": "room-aula-221"
    },
    {
      "id": "room-aula-222",
      "label": "AULA 222",
      "aliases": [
        "aula 222",
        "222"
      ],
      "category": "aula",
      "bbox": {
        "x": 963.493344233849,
        "y": 396.6334243954566,
        "width": 95.84867742795882,
        "height": 116.93032368526383
      },
      "shapeId": "room-aula-222"
    },
    {
      "id": "room-aula-211a",
      "label": "AULA 211A",
      "aliases": [
        "aula 211a"
      ],
      "category": "aula",
      "bbox": {
        "x": 1286.7667644654368,
        "y": 417.98674356682454,
        "width": 36.17133167753741,
        "height": 115.85698958630587
      },
      "shapeId": "room-aula-211a"
    },
    {
      "id": "room-aula-211b",
      "label": "AULA 211B",
      "aliases": [
        "aula 211b"
      ],
      "category": "aula",
      "bbox": {
        "x": 1287.4600175899425,
        "y": 333.8100135494519,
        "width": 35.63466577940039,
        "height": 84.7303199826647
      },
      "shapeId": "room-aula-211b"
    },
    {
      "id": "room-aula-211c",
      "label": "AULA 211C",
      "aliases": [
        "aula 211c"
      ],
      "category": "aula",
      "bbox": {
        "x": 1287.2666443948845,
        "y": 268.0666416856268,
        "width": 35.63466577940039,
        "height": 66.4836508091829
      },
      "shapeId": "room-aula-211c"
    },
    {
      "id": "room-laboratorio-de-sistemas-liquidos",
      "label": "LABORATORIO DE SISTEMAS LÍQUIDOS",
      "aliases": [
        "laboratorio de sistemas liquidos"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 1352.3967206435627,
        "y": 316.17002808635505,
        "width": 77.49466714443156,
        "height": 50.9203203860302
      },
      "shapeId": "room-laboratorio-de-sistemas-liquidos"
    },
    {
      "id": "room-banos-hombres",
      "label": "BAÑOS HOMBRES",
      "aliases": [
        "banos hombres"
      ],
      "category": "bano",
      "bbox": {
        "x": 1118.030057991672,
        "y": 454.87003271341086,
        "width": 60.32133322301297,
        "height": 78.8269876927975
      },
      "shapeId": "room-banos-hombres"
    },
    {
      "id": "room-lab-de-electro-optica",
      "label": "LAB. DE ELECTRO ÓPTICA",
      "aliases": [
        "lab. de electro optica",
        "lab de electro optica"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 1058.353346553533,
        "y": 600.5799832798427,
        "width": 56.13533746582016,
        "height": 99.22032331272817
      },
      "shapeId": "room-lab-de-electro-optica"
    },
    {
      "id": "room-depto-fisica",
      "label": "DEPTO FÍSICA",
      "aliases": [
        "depto fisica"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1177.760008312511,
        "y": 455.21334006949974,
        "width": 58.71133333894659,
        "height": 78.29031889185126
      },
      "shapeId": "room-depto-fisica"
    },
    {
      "id": "room-lab-de-laser",
      "label": "LAB. DE LÁSER",
      "aliases": [
        "lab. de laser",
        "lab de laser"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 814.1799703734088,
        "y": 599.9366803968176,
        "width": 56.13533746582027,
        "height": 99.22032331272817
      },
      "shapeId": "room-lab-de-laser"
    },
    {
      "id": "room-laboratorio-de-fisica-iii",
      "label": "LABORATORIO DE FÍSICA III",
      "aliases": [
        "laboratorio de fisica iii",
        "laboratorio 1",
        "laboratorio 2"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 580.7233971166261,
        "y": 769.5466834887052,
        "width": 225.18535375828696,
        "height": 62.72698846869878
      },
      "shapeId": "room-laboratorio-de-fisica-iii"
    },
    {
      "id": "room-laboratorio-de-fisica-ii",
      "label": "LABORATORIO DE FÍSICA II",
      "aliases": [
        "laboratorio de fisica ii",
        "laboratorio 1",
        "laboratorio 2",
        "laboratorio 3"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 498.5199644865827,
        "y": 537.7034373296551,
        "width": 82.43200698315422,
        "height": 295.6403338134596
      },
      "shapeId": "room-laboratorio-de-fisica-ii"
    },
    {
      "id": "room-laboratorio-de-fisica-i",
      "label": "LABORATORIO DE FÍSICA I",
      "aliases": [
        "laboratorio de fisica i",
        "laboratorio 1",
        "laboratorio 2"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 1349.0400455270951,
        "y": 368.4601635894469,
        "width": 82.43200698315422,
        "height": 401.36365498745727
      },
      "shapeId": "room-laboratorio-de-fisica-i"
    },
    {
      "id": "room-lab-haces-dirigidos",
      "label": "LAB. HACES DIRIGIDOS",
      "aliases": [
        "lab. haces dirigidos",
        "lab haces dirigidos"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 499.3666729075122,
        "y": 322.33000534085085,
        "width": 66.86867732511234,
        "height": 34.28365411245238
      },
      "shapeId": "room-lab-haces-dirigidos"
    },
    {
      "id": "room-banos-damas",
      "label": "BAÑOS DAMAS",
      "aliases": [
        "banos damas"
      ],
      "category": "bano",
      "bbox": {
        "x": 722.7100290256013,
        "y": 453.51332873471756,
        "width": 89.94534597948632,
        "height": 80.97365413924626
      },
      "shapeId": "room-banos-damas"
    }
  ]
};

export default piso2Manifest;
