// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from '../types';
import type { FloorManifest } from '../types';

const plantabajaManifest: FloorManifest = {
  "floorId": "plantabaja",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-salon-polideportivo",
      "label": "SALÓN POLIDEPORTIVO",
      "aliases": [
        "salon polideportivo"
      ],
      "category": "otro",
      "bbox": {
        "x": 754.5035410400001,
        "y": 190.62120081370702,
        "width": 356.3777499999999,
        "height": 198.562691681406
      },
      "shapeId": "room-salon-polideportivo"
    },
    {
      "id": "room-direccion-de-personal",
      "label": "DIRECCIÓN DE PERSONAL",
      "aliases": [
        "direccion de personal"
      ],
      "category": "otro",
      "bbox": {
        "x": 1169.15140104,
        "y": 151.733378367578,
        "width": 114.93224000000009,
        "height": 80.6796029595906
      },
      "shapeId": "room-direccion-de-personal"
    },
    {
      "id": "room-vestuario-fem",
      "label": "VESTUARIO FEM",
      "aliases": [
        "vestuario fem"
      ],
      "category": "otro",
      "bbox": {
        "x": 1109.44320104,
        "y": 190.659116548235,
        "width": 55.9518700000001,
        "height": 100.71436912293868
      },
      "shapeId": "room-vestuario-fem"
    },
    {
      "id": "room-vestuario-masc",
      "label": "VESTUARIO MASC",
      "aliases": [
        "vestuario masc"
      ],
      "category": "otro",
      "bbox": {
        "x": 1110.47210104,
        "y": 290.39892117005,
        "width": 55.9518700000001,
        "height": 93.95276435739095
      },
      "shapeId": "room-vestuario-masc"
    },
    {
      "id": "room-fondo-del-cei",
      "label": "FONDO DEL CEI",
      "aliases": [
        "fondo del cei"
      ],
      "category": "otro",
      "bbox": {
        "x": 636.9803510400001,
        "y": 152.79411970516702,
        "width": 118.52801,
        "height": 79.13761214142147
      },
      "shapeId": "room-fondo-del-cei"
    },
    {
      "id": "room-sala-de-pc",
      "label": "SALA DE PC",
      "aliases": [
        "sala de pc"
      ],
      "category": "sala",
      "bbox": {
        "x": 752.84821104,
        "y": 153.96082197942798,
        "width": 112.28511000000003,
        "height": 35.58948784387022
      },
      "shapeId": "room-sala-de-pc"
    },
    {
      "id": "room-salon-de-actos",
      "label": "SALÓN DE ACTOS",
      "aliases": [
        "salon de actos"
      ],
      "category": "otro",
      "bbox": {
        "x": 492.51199465991783,
        "y": 306.3600859145208,
        "width": 145.23925420616922,
        "height": 218.42637736073766
      },
      "shapeId": "room-salon-de-actos"
    },
    {
      "id": "room-decanato",
      "label": "DECANATO",
      "aliases": [
        "decanato"
      ],
      "category": "otro",
      "bbox": {
        "x": 489.3874006165736,
        "y": 531.0366033946259,
        "width": 81.10206946387041,
        "height": 117.38432325758527
      },
      "shapeId": "room-decanato"
    },
    {
      "id": "room-sala-de-reuniones",
      "label": "SALA DE REUNIONES",
      "aliases": [
        "sala de reuniones"
      ],
      "category": "sala",
      "bbox": {
        "x": 574.39374104,
        "y": 591.8132371296531,
        "width": 87.19992100000002,
        "height": 52.3000226620602
      },
      "shapeId": "room-sala-de-reuniones"
    },
    {
      "id": "room-servicios-generales",
      "label": "SERVICIOS GENERALES",
      "aliases": [
        "servicios generales"
      ],
      "category": "otro",
      "bbox": {
        "x": 810.67084104,
        "y": 566.455132518158,
        "width": 54.95200299999999,
        "height": 103.17450574462055
      },
      "shapeId": "room-servicios-generales"
    },
    {
      "id": "room-secretaria-administrativa",
      "label": "SECRETARÍA ADMINISTRATIVA",
      "aliases": [
        "secretaria administrativa"
      ],
      "category": "otro",
      "bbox": {
        "x": 638.69287104,
        "y": 762.3817073665041,
        "width": 167.20198000000005,
        "height": 65.55693657518191
      },
      "shapeId": "room-secretaria-administrativa"
    },
    {
      "id": "room-vice-decanato",
      "label": "VICE DECANATO",
      "aliases": [
        "vice decanato"
      ],
      "category": "otro",
      "bbox": {
        "x": 492.95120104,
        "y": 766.121802592682,
        "width": 53.735855000000015,
        "height": 61.20200449504807
      },
      "shapeId": "room-vice-decanato"
    },
    {
      "id": "room-consejo-estudiantil",
      "label": "CONSEJO ESTUDIANTIL",
      "aliases": [
        "consejo estudiantil"
      ],
      "category": "otro",
      "bbox": {
        "x": 875.0388810400001,
        "y": 477.581222059544,
        "width": 59.53801299999998,
        "height": 40.270752314702975
      },
      "shapeId": "room-consejo-estudiantil"
    },
    {
      "id": "room-depto-deportes",
      "label": "DEPTO DEPORTES",
      "aliases": [
        "depto deportes"
      ],
      "category": "departamento",
      "bbox": {
        "x": 988.83808104,
        "y": 442.635292450118,
        "width": 57.89864,
        "height": 77.0610380301585
      },
      "shapeId": "room-depto-deportes"
    },
    {
      "id": "room-mesa-de-entradas",
      "label": "MESA DE ENTRADAS",
      "aliases": [
        "mesa de entradas"
      ],
      "category": "otro",
      "bbox": {
        "x": 1056.76750104,
        "y": 566.6248858318401,
        "width": 59.3399159999999,
        "height": 103.17450574462043
      },
      "shapeId": "room-mesa-de-entradas"
    },
    {
      "id": "room-bano-caballeros",
      "label": "BAÑO CABALLEROS",
      "aliases": [
        "bano caballeros"
      ],
      "category": "bano",
      "bbox": {
        "x": 1117.92280104,
        "y": 447.73112908568004,
        "width": 57.89863999999989,
        "height": 76.12573175985511
      },
      "shapeId": "room-bano-caballeros"
    },
    {
      "id": "room-fotocopiadora",
      "label": "FOTOCOPIADORA",
      "aliases": [
        "fotocopiadora"
      ],
      "category": "otro",
      "bbox": {
        "x": 1176.21230104,
        "y": 443.99694761385507,
        "width": 104.65334000000007,
        "height": 79.83177370537675
      },
      "shapeId": "room-fotocopiadora"
    },
    {
      "id": "room-departamentos-de-alumnos",
      "label": "DEPARTAMENTOS DE ALUMNOS",
      "aliases": [
        "departamentos de alumnos"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1352.2780010400002,
        "y": 444.87781137494306,
        "width": 79.21072400000003,
        "height": 185.506423307523
      },
      "shapeId": "room-departamentos-de-alumnos"
    },
    {
      "id": "room-servicios-de-computacion",
      "label": "SERVICIOS DE COMPUTACIÓN",
      "aliases": [
        "servicios de computacion"
      ],
      "category": "otro",
      "bbox": {
        "x": 1351.20710104,
        "y": 359.0872520343141,
        "width": 80.53388999999993,
        "height": 87.87622413009512
      },
      "shapeId": "room-servicios-de-computacion"
    },
    {
      "id": "room-oficina-adm",
      "label": "OFICINA ADM",
      "aliases": [
        "oficina adm"
      ],
      "category": "oficina",
      "bbox": {
        "x": 1352.75850104,
        "y": 308.5050596988801,
        "width": 80.53388999999993,
        "height": 52.39286966331895
      },
      "shapeId": "room-oficina-adm"
    },
    {
      "id": "room-admision",
      "label": "ADMISIÓN",
      "aliases": [
        "admision"
      ],
      "category": "otro",
      "bbox": {
        "x": 1189.82480104,
        "y": 564.090900276998,
        "width": 108.30582000000004,
        "height": 27.51265035729807
      },
      "shapeId": "room-admision"
    },
    {
      "id": "room-comunicacion-universitaria",
      "label": "COMUNICACIÓN UNIVERSITARIA",
      "aliases": [
        "comunicacion universitaria"
      ],
      "category": "otro",
      "bbox": {
        "x": 1266.21440104,
        "y": 654.3253021909791,
        "width": 82.78874999999994,
        "height": 40.76873274789352
      },
      "shapeId": "room-comunicacion-universitaria"
    },
    {
      "id": "room-direcc-gral-academica",
      "label": "DIRECC. GRAL. ACADÉMICA",
      "aliases": [
        "direcc. gral. academica",
        "direcc gral academica"
      ],
      "category": "otro",
      "bbox": {
        "x": 1353.45710104,
        "y": 656.0349273156801,
        "width": 79.21072400000003,
        "height": 37.522640188114224
      },
      "shapeId": "room-direcc-gral-academica"
    },
    {
      "id": "room-secretaria-academica",
      "label": "SECRETARIA ACADÉMICA",
      "aliases": [
        "secretaria academica"
      ],
      "category": "otro",
      "bbox": {
        "x": 1350.95880104,
        "y": 694.4441376675621,
        "width": 79.21072400000003,
        "height": 66.87329491957507
      },
      "shapeId": "room-secretaria-academica"
    },
    {
      "id": "room-direccion-principal-contable",
      "label": "DIRECCIÓN PRINCIPAL CONTABLE",
      "aliases": [
        "direccion principal contable"
      ],
      "category": "otro",
      "bbox": {
        "x": 1169.12750104,
        "y": 721.2995541012351,
        "width": 147.42284999999993,
        "height": 103.17450574462043
      },
      "shapeId": "room-direccion-principal-contable"
    },
    {
      "id": "room-tesoreria",
      "label": "TESORERÍA",
      "aliases": [
        "tesoreria"
      ],
      "category": "otro",
      "bbox": {
        "x": 1115.62270104,
        "y": 721.6011555732381,
        "width": 53.30761299999995,
        "height": 103.96882345631491
      },
      "shapeId": "room-tesoreria"
    },
    {
      "id": "room-bici",
      "label": "BICI",
      "aliases": [
        "bici"
      ],
      "category": "otro",
      "bbox": {
        "x": 809.03913104,
        "y": 727.2329645465211,
        "width": 24.312823999999978,
        "height": 103.17450574462043
      },
      "shapeId": "room-bici"
    },
    {
      "id": "room-secretaria-de-posgrado",
      "label": "SECRETARÍA DE POSGRADO",
      "aliases": [
        "secretaria de posgrado"
      ],
      "category": "otro",
      "bbox": {
        "x": 639.83331104,
        "y": 444.9493265438631,
        "width": 110.99838,
        "height": 77.54669373379409
      },
      "shapeId": "room-secretaria-de-posgrado"
    },
    {
      "id": "room-bano-damas",
      "label": "BAÑO DAMAS",
      "aliases": [
        "bano damas"
      ],
      "category": "bano",
      "bbox": {
        "x": 750.28174104,
        "y": 445.7079903469341,
        "width": 56.89611100000002,
        "height": 55.20547556568988
      },
      "shapeId": "room-bano-damas"
    }
  ]
};

export default plantabajaManifest;
