// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from '../types';
import type { FloorManifest } from '../types';

const subsueloManifest: FloorManifest = {
  "floorId": "subsuelo",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-taller-de-mecanica-de-ensenanza",
      "label": "TALLER DE MECÁNICA DE ENSEÑANZA",
      "aliases": [
        "taller de mecanica de ensenanza"
      ],
      "category": "otro",
      "bbox": {
        "x": 757.846862,
        "y": 175.13408900000002,
        "width": 224.66516000000001,
        "height": 86.84912899999995
      },
      "shapeId": "room-taller-de-mecanica-de-ensenanza"
    },
    {
      "id": "room-aula-e32",
      "label": "AULA E32",
      "aliases": [
        "aula e32"
      ],
      "category": "aula",
      "bbox": {
        "x": 1069.0551819999998,
        "y": 265.664645,
        "width": 79.42843599999992,
        "height": 121.45364000000001
      },
      "shapeId": "room-aula-e32"
    },
    {
      "id": "room-aula-e33",
      "label": "AULA E33",
      "aliases": [
        "aula e33"
      ],
      "category": "aula",
      "bbox": {
        "x": 1096.2679819999998,
        "y": 174.99992600000002,
        "width": 54.3135299999999,
        "height": 85.53412599999996
      },
      "shapeId": "room-aula-e33"
    },
    {
      "id": "room-comedor",
      "label": "COMEDOR",
      "aliases": [
        "comedor"
      ],
      "category": "otro",
      "bbox": {
        "x": 1337.364482,
        "y": 340.85695499999997,
        "width": 159.49271999999996,
        "height": 230.32227
      },
      "shapeId": "room-comedor"
    },
    {
      "id": "room-comedor-docente",
      "label": "COMEDOR DOCENTE",
      "aliases": [
        "comedor docente"
      ],
      "category": "otro",
      "bbox": {
        "x": 1411.1103819999998,
        "y": 570.253405,
        "width": 83.46499599999993,
        "height": 57.618922999999995
      },
      "shapeId": "room-comedor-docente"
    },
    {
      "id": "room-aula-e14",
      "label": "AULA E14",
      "aliases": [
        "aula e14"
      ],
      "category": "aula",
      "bbox": {
        "x": 1222.9347819999998,
        "y": 571.276535,
        "width": 96.48795300000006,
        "height": 68.06777999999997
      },
      "shapeId": "room-aula-e14"
    },
    {
      "id": "room-aula-e16",
      "label": "AULA E16",
      "aliases": [
        "aula e16"
      ],
      "category": "aula",
      "bbox": {
        "x": 1215.3794819999998,
        "y": 486.094565,
        "width": 120.98738000000003,
        "height": 86.272606
      },
      "shapeId": "room-aula-e16"
    },
    {
      "id": "room-depto-mecanica-aplicada",
      "label": "DEPTO. MECÁNICA APLICADA",
      "aliases": [
        "depto. mecanica aplicada",
        "depto mecanica aplicada"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1018.989182,
        "y": 423.622575,
        "width": 191.12401999999997,
        "height": 57.401463000000035
      },
      "shapeId": "room-depto-mecanica-aplicada"
    },
    {
      "id": "room-oficinas-de-lab-de-fluido-dinamico",
      "label": "OFICINAS DE LAB. DE FLUIDO-DINÁMICO",
      "aliases": [
        "oficinas de lab. de fluido-dinamico",
        "oficinas de lab de fluido-dinamico"
      ],
      "category": "oficina",
      "bbox": {
        "x": 788.367132,
        "y": 428.569755,
        "width": 180.43146000000002,
        "height": 57.44633900000008
      },
      "shapeId": "room-oficinas-de-lab-de-fluido-dinamico"
    },
    {
      "id": "room-lab-solidos-amorfos",
      "label": "LAB.SOLIDOS AMORFOS",
      "aliases": [
        "lab.solidos amorfos",
        "labsolidos amorfos"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 491.120882,
        "y": 341.85179500000004,
        "width": 84.56061600000004,
        "height": 47.597622
      },
      "shapeId": "room-lab-solidos-amorfos"
    },
    {
      "id": "room-oficina-sol-amor",
      "label": "OFICINA SOL. AMOR.",
      "aliases": [
        "oficina sol. amor.",
        "oficina sol amor"
      ],
      "category": "oficina",
      "bbox": {
        "x": 522.891972,
        "y": 391.01988500000004,
        "width": 64.59037799999999,
        "height": 56.770427999999924
      },
      "shapeId": "room-oficina-sol-amor"
    },
    {
      "id": "room-aula-e29",
      "label": "AULA E29",
      "aliases": [
        "aula e29"
      ],
      "category": "aula",
      "bbox": {
        "x": 579.783452,
        "y": 572.366045,
        "width": 90.75425700000005,
        "height": 94.75348699999995
      },
      "shapeId": "room-aula-e29"
    },
    {
      "id": "room-aula-e7",
      "label": "AULA E7",
      "aliases": [
        "aula e7"
      ],
      "category": "aula",
      "bbox": {
        "x": 579.767882,
        "y": 668.059895,
        "width": 89.01064299999996,
        "height": 83.47553300000004
      },
      "shapeId": "room-aula-e7"
    },
    {
      "id": "room-aula-e5",
      "label": "AULA E5",
      "aliases": [
        "aula e5"
      ],
      "category": "aula",
      "bbox": {
        "x": 493.911622,
        "y": 705.352005,
        "width": 81.96385200000003,
        "height": 88.03649900000005
      },
      "shapeId": "room-aula-e5"
    },
    {
      "id": "room-aula-e3",
      "label": "AULA E3",
      "aliases": [
        "aula e3"
      ],
      "category": "aula",
      "bbox": {
        "x": 492.62280200000004,
        "y": 793.572895,
        "width": 82.588547,
        "height": 97.56720700000005
      },
      "shapeId": "room-aula-e3"
    },
    {
      "id": "room-aula-e1",
      "label": "AULA E1",
      "aliases": [
        "aula e1"
      ],
      "category": "aula",
      "bbox": {
        "x": 581.005252,
        "y": 895.706685,
        "width": 68.38201900000001,
        "height": 82.19892900000002
      },
      "shapeId": "room-aula-e1"
    },
    {
      "id": "room-jardin-maternal",
      "label": "JARDÍN MATERNAL",
      "aliases": [
        "jardin maternal"
      ],
      "category": "otro",
      "bbox": {
        "x": 641.876892,
        "y": 484.151845,
        "width": 117.30956000000003,
        "height": 28.858754999999974
      },
      "shapeId": "room-jardin-maternal"
    },
    {
      "id": "room-aula-e8",
      "label": "AULA E8",
      "aliases": [
        "aula e8"
      ],
      "category": "aula",
      "bbox": {
        "x": 1310.0860819999998,
        "y": 733.298545,
        "width": 93.93843100000004,
        "height": 90.42941299999995
      },
      "shapeId": "room-aula-e8"
    },
    {
      "id": "room-aula-e10",
      "label": "AULA E10",
      "aliases": [
        "aula e10"
      ],
      "category": "aula",
      "bbox": {
        "x": 1296.8921819999998,
        "y": 641.634475,
        "width": 75.228386,
        "height": 91.059891
      },
      "shapeId": "room-aula-e10"
    },
    {
      "id": "room-gab-e11",
      "label": "GAB. E11",
      "aliases": [
        "gab. e11",
        "gab e11"
      ],
      "category": "otro",
      "bbox": {
        "x": 1157.577282,
        "y": 752.414085,
        "width": 56.94896700000004,
        "height": 50.699509000000035
      },
      "shapeId": "room-gab-e11"
    },
    {
      "id": "room-aula-e9",
      "label": "AULA E9",
      "aliases": [
        "aula e9"
      ],
      "category": "aula",
      "bbox": {
        "x": 608.541322,
        "y": 753.126545,
        "width": 155.05991000000006,
        "height": 68.30915100000004
      },
      "shapeId": "room-aula-e9"
    },
    {
      "id": "room-sala-de-compu",
      "label": "SALA DE COMPU",
      "aliases": [
        "sala de compu"
      ],
      "category": "sala",
      "bbox": {
        "x": 1268.3831819999998,
        "y": 826.3896649999999,
        "width": 70.19764699999996,
        "height": 69.95072200000004
      },
      "shapeId": "room-sala-de-compu"
    }
  ]
};

export default subsueloManifest;
