// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
import type { FloorManifest } from './types';
// ── PC floors ──
import piso1Svg from './pc/piso1SvgXml';
import piso1Manifest from './pc/piso1.manifest';
import piso2Svg from './pc/piso2SvgXml';
import piso2Manifest from './pc/piso2.manifest';
import piso3Svg from './pc/piso3SvgXml';
import piso3Manifest from './pc/piso3.manifest';
import piso4Svg from './pc/piso4SvgXml';
import piso4Manifest from './pc/piso4.manifest';
import piso5Svg from './pc/piso5SvgXml';
import piso5Manifest from './pc/piso5.manifest';
import plantabajaSvg from './pc/plantabajaSvgXml';
import plantabajaManifest from './pc/plantabaja.manifest';
import subsueloSvg from './pc/subsueloSvgXml';
import subsueloManifest from './pc/subsuelo.manifest';

export type FloorEntry = {
  id: string;
  label: string;
  svgXml: string;
  manifest: FloorManifest;
};

export type BuildingEntry = {
  id: string;
  label: string;
  shortLabel: string;
  floorOrder: string[];
  floors: Record<string, FloorEntry>;
};

// Add new buildings/floors in scripts/build_floor_manifest.js BUILDING_CONFIGS and re-run.
export const BUILDINGS: Record<string, BuildingEntry> = {
  pc: {
    id: 'pc',
    label: 'Paseo Colón',
    shortLabel: 'PC',
    floorOrder: ['piso1', 'piso2', 'piso3', 'piso4', 'piso5', 'plantabaja', 'subsuelo'],
    floors: {
      piso1: { id: 'piso1', label: 'Piso 1', svgXml: piso1Svg, manifest: piso1Manifest },
      piso2: { id: 'piso2', label: 'Piso 2', svgXml: piso2Svg, manifest: piso2Manifest },
      piso3: { id: 'piso3', label: 'Piso 3', svgXml: piso3Svg, manifest: piso3Manifest },
      piso4: { id: 'piso4', label: 'Piso 4', svgXml: piso4Svg, manifest: piso4Manifest },
      piso5: { id: 'piso5', label: 'Piso 5', svgXml: piso5Svg, manifest: piso5Manifest },
      plantabaja: { id: 'plantabaja', label: 'Planta Baja', svgXml: plantabajaSvg, manifest: plantabajaManifest },
      subsuelo: { id: 'subsuelo', label: 'Subsuelo', svgXml: subsueloSvg, manifest: subsueloManifest },
    },
  },
  lh: {
    id: 'lh',
    label: 'Las Heras',
    shortLabel: 'LH',
    floorOrder: [],
    floors: {
      
    },
  },
  cu: {
    id: 'cu',
    label: 'Ciudad Universitaria',
    shortLabel: 'CU',
    floorOrder: [],
    floors: {

    },
  },
};

export const BUILDING_ORDER: string[] = ['pc', 'lh', 'cu'];

// Flat list of all floors across all buildings (used for cross-building search).
export const ALL_FLOORS: FloorEntry[] = BUILDING_ORDER.flatMap(
  bid => BUILDINGS[bid].floorOrder.map(fid => BUILDINGS[bid].floors[fid])
);
