// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
import type { FloorManifest } from './types';
// ── PC floors ──
import piso4Svg from './pc/piso4SvgXml';
import piso4Manifest from './pc/piso4.manifest';
import subsuelo1Svg from './pc/subsuelo1SvgXml';
import subsuelo1Manifest from './pc/subsuelo1.manifest';
// ── LH floors ──
import piso3Svg from './lh/piso3SvgXml';
import piso3Manifest from './lh/piso3.manifest';

export type FloorEntry = {
  id: string;
  label: string;
  svgXml: string;
  manifest: FloorManifest;
};

export type BuildingEntry = {
  id: string;
  label: string;
  shortLabel: string;
  floorOrder: string[];
  floors: Record<string, FloorEntry>;
};

// Add new buildings/floors in scripts/build_floor_manifest.js BUILDING_CONFIGS and re-run.
export const BUILDINGS: Record<string, BuildingEntry> = {
  pc: {
    id: 'pc',
    label: 'Paseo Colón',
    shortLabel: 'PC',
    floorOrder: ['piso4', 'subsuelo1'],
    floors: {
      piso4: { id: 'piso4', label: 'Piso 4', svgXml: piso4Svg, manifest: piso4Manifest },
      subsuelo1: { id: 'subsuelo1', label: 'Subsuelo 1', svgXml: subsuelo1Svg, manifest: subsuelo1Manifest },
    },
  },
  lh: {
    id: 'lh',
    label: 'Las Heras',
    shortLabel: 'LH',
    floorOrder: ['piso3'],
    floors: {
      piso3: { id: 'piso3', label: 'Piso 3', svgXml: piso3Svg, manifest: piso3Manifest },
    },
  },
  cu: {
    id: 'cu',
    label: 'Ciudad Universitaria',
    shortLabel: 'CU',
    floorOrder: [],
    floors: {

    },
  },
};

export const BUILDING_ORDER: string[] = ['pc', 'lh', 'cu'];

// Flat list of all floors across all buildings (used for cross-building search).
export const ALL_FLOORS: FloorEntry[] = BUILDING_ORDER.flatMap(
  bid => BUILDINGS[bid].floorOrder.map(fid => BUILDINGS[bid].floors[fid])
);
