// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
import type { FloorManifest } from './types';
import piso4Svg from './piso4SvgXml';
import piso4Manifest from './piso4.manifest';
import subsuelo1Svg from './subsuelo1SvgXml';
import subsuelo1Manifest from './subsuelo1.manifest';

export type FloorEntry = {
  id: string;
  label: string;
  svgXml: string;
  manifest: FloorManifest;
};

// Add new floors in scripts/build_floor_manifest.js FLOOR_CONFIGS and re-run.
export const FLOORS: Record<string, FloorEntry> = {
  piso4: { id: 'piso4', label: 'Piso 4', svgXml: piso4Svg, manifest: piso4Manifest },
  subsuelo1: { id: 'subsuelo1', label: 'Primer Subsuelo', svgXml: subsuelo1Svg, manifest: subsuelo1Manifest },
};

export const FLOOR_ORDER: string[] = ['piso4', 'subsuelo1'];
