// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from './types';
import type { FloorManifest } from './types';

const piso4Manifest: FloorManifest = {
  "floorId": "piso4",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-laboratorios",
      "label": "LABORATORIOS",
      "aliases": [
        "laboratorios"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 574.90363,
        "y": 106.20985,
        "width": 290.535,
        "height": 40.428265
      },
      "shapeId": "room-laboratorios"
    },
    {
      "id": "room-lab-medios-porosos",
      "label": "LAB MEDIOS POROSOS",
      "aliases": [
        "lab medios porosos"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 640,
        "y": 146.63812,
        "width": 115.803,
        "height": 40.428265
      },
      "shapeId": "room-lab-medios-porosos"
    },
    {
      "id": "room-sala-lateral-superior",
      "label": "SALA LATERAL SUPERIOR",
      "aliases": [
        "sala lateral superior"
      ],
      "category": "sala",
      "bbox": {
        "x": 752.37689,
        "y": 153.49037,
        "width": 113.74732,
        "height": 183.64026
      },
      "shapeId": "room-sala-lateral-superior"
    },
    {
      "id": "room-aula-403",
      "label": "AULA 403",
      "aliases": [
        "aula 403",
        "403"
      ],
      "category": "aula",
      "bbox": {
        "x": 491.30621,
        "y": 265.86725,
        "width": 148.009,
        "height": 214.47537
      },
      "shapeId": "room-aula-403"
    },
    {
      "id": "room-aula-405",
      "label": "AULA 405",
      "aliases": [
        "aula 405",
        "405"
      ],
      "category": "aula",
      "bbox": {
        "x": 492.67667,
        "y": 484.11136,
        "width": 84.625,
        "height": 61.327625
      },
      "shapeId": "room-aula-405"
    },
    {
      "id": "room-bedelia",
      "label": "BEDELIA",
      "aliases": [
        "bedelia"
      ],
      "category": "otro",
      "bbox": {
        "x": 491.31055,
        "y": 546.54688,
        "width": 87.21483999999992,
        "height": 51.82617000000005
      },
      "shapeId": "room-bedelia"
    },
    {
      "id": "room-depto-de-ing-sanitaria",
      "label": "DEPTO DE ING SANITARIA",
      "aliases": [
        "depto de ing sanitaria"
      ],
      "category": "departamento",
      "bbox": {
        "x": 491.31055,
        "y": 592.0918,
        "width": 85.27734000000004,
        "height": 119.19335999999998
      },
      "shapeId": "room-depto-de-ing-sanitaria"
    },
    {
      "id": "room-inst-ing-biomedica",
      "label": "INST. ING. BIOMEDICA",
      "aliases": [
        "inst. ing. biomedica",
        "inst ing biomedica"
      ],
      "category": "instituto",
      "bbox": {
        "x": 491.79504,
        "y": 710.80133,
        "width": 85.277,
        "height": 69.771912
      },
      "shapeId": "room-inst-ing-biomedica"
    },
    {
      "id": "room-inst-ing-biomed",
      "label": "INST. ING. BIOMED.",
      "aliases": [
        "inst. ing. biomed.",
        "inst ing biomed"
      ],
      "category": "instituto",
      "bbox": {
        "x": 630.40686,
        "y": 710.57819,
        "width": 67.836998,
        "height": 69.20771
      },
      "shapeId": "room-inst-ing-biomed"
    },
    {
      "id": "room-aula-411",
      "label": "AULA 411",
      "aliases": [
        "aula 411",
        "411"
      ],
      "category": "aula",
      "bbox": {
        "x": 629.88525,
        "y": 647.32825,
        "width": 121.132,
        "height": 65.895691
      },
      "shapeId": "room-aula-411"
    },
    {
      "id": "room-laboratorios-2",
      "label": "LABORATORIOS",
      "aliases": [
        "laboratorios"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 698.24414,
        "y": 711.26337,
        "width": 108.266,
        "height": 63.72591
      },
      "shapeId": "room-laboratorios-2"
    },
    {
      "id": "room-ing-sanit",
      "label": "ING. SANIT.",
      "aliases": [
        "ing. sanit.",
        "ing sanit"
      ],
      "category": "otro",
      "bbox": {
        "x": 751.01709,
        "y": 646.35919,
        "width": 55.236,
        "height": 64.926636
      },
      "shapeId": "room-ing-sanit"
    },
    {
      "id": "room-aula-400",
      "label": "AULA 400",
      "aliases": [
        "aula 400",
        "400"
      ],
      "category": "aula",
      "bbox": {
        "x": 809.25055,
        "y": 678.37262,
        "width": 185.69594,
        "height": 95.93148
      },
      "shapeId": "room-aula-400"
    },
    {
      "id": "room-aula-408",
      "label": "AULA 408",
      "aliases": [
        "aula 408",
        "408"
      ],
      "category": "aula",
      "bbox": {
        "x": 994.94647,
        "y": 678.37262,
        "width": 116.48823,
        "height": 96.616707
      },
      "shapeId": "room-aula-408"
    },
    {
      "id": "room-aula-422",
      "label": "AULA 422",
      "aliases": [
        "aula 422",
        "422"
      ],
      "category": "aula",
      "bbox": {
        "x": 970.96362,
        "y": 600.9422,
        "width": 82.226997,
        "height": 47.96574
      },
      "shapeId": "room-aula-422"
    },
    {
      "id": "room-aula-416",
      "label": "AULA 416",
      "aliases": [
        "aula 416",
        "416"
      ],
      "category": "aula",
      "bbox": {
        "x": 1110.7495,
        "y": 711.26337,
        "width": 108.95075,
        "height": 65.096359
      },
      "shapeId": "room-aula-416"
    },
    {
      "id": "room-aula-414",
      "label": "AULA 414",
      "aliases": [
        "aula 414",
        "414"
      ],
      "category": "aula",
      "bbox": {
        "x": 1153.9187,
        "y": 647.53748,
        "width": 128.82227,
        "height": 62.355461
      },
      "shapeId": "room-aula-414"
    },
    {
      "id": "room-aula-412",
      "label": "AULA 412",
      "aliases": [
        "aula 412",
        "412"
      ],
      "category": "aula",
      "bbox": {
        "x": 1219.015,
        "y": 712.63385,
        "width": 63.726002,
        "height": 63.040688
      },
      "shapeId": "room-aula-412"
    },
    {
      "id": "room-dpto-naval",
      "label": "DPTO. NAVAL",
      "aliases": [
        "dpto. naval",
        "dpto naval"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1277.2592,
        "y": 779.10065,
        "width": 66.467003,
        "height": 78.115631
      },
      "shapeId": "room-dpto-naval"
    },
    {
      "id": "room-oficina",
      "label": "OFICINA",
      "aliases": [
        "oficina"
      ],
      "category": "oficina",
      "bbox": {
        "x": 1346.4668,
        "y": 724.28265,
        "width": 81.542,
        "height": 50.706638
      },
      "shapeId": "room-oficina"
    },
    {
      "id": "room-sala-pc",
      "label": "SALA PC",
      "aliases": [
        "sala pc"
      ],
      "category": "sala",
      "bbox": {
        "x": 1344.4111,
        "y": 585.18201,
        "width": 80.856529,
        "height": 139.10065
      },
      "shapeId": "room-sala-pc"
    },
    {
      "id": "room-sala-pc-2",
      "label": "SALA PC",
      "aliases": [
        "sala pc"
      ],
      "category": "sala",
      "bbox": {
        "x": 1344.4111,
        "y": 585.18201,
        "width": 80.856529,
        "height": 139.10065
      },
      "shapeId": "room-sala-pc-2"
    },
    {
      "id": "room-servicio-de-computacion",
      "label": "Servicio de computación",
      "aliases": [
        "servicio de computacion"
      ],
      "category": "otro",
      "bbox": {
        "x": 1344.4111,
        "y": 476.9165,
        "width": 82.912003,
        "height": 108.26553
      },
      "shapeId": "room-servicio-de-computacion"
    },
    {
      "id": "room-comunicacion-e-intercambios-academ",
      "label": "COMUNICACIÓN E INTERCAMBIOS ACADÉM.",
      "aliases": [
        "comunicacion e intercambios academ.",
        "comunicacion e intercambios academ"
      ],
      "category": "otro",
      "bbox": {
        "x": 1052.5054,
        "y": 515.9743,
        "width": 260.38501,
        "height": 26.72377
      },
      "shapeId": "room-comunicacion-e-intercambios-academ"
    },
    {
      "id": "room-sala-del-mainframe",
      "label": "SALA DEL MAINFRAME",
      "aliases": [
        "sala del mainframe"
      ],
      "category": "sala",
      "bbox": {
        "x": 1345.0964,
        "y": 357.68738,
        "width": 84.282654,
        "height": 119.91435
      },
      "shapeId": "room-sala-del-mainframe"
    },
    {
      "id": "room-aula-430",
      "label": "AULA 430",
      "aliases": [
        "aula 430",
        "430"
      ],
      "category": "aula",
      "bbox": {
        "x": 1276.7452,
        "y": 402.31262,
        "width": 5.7981277,
        "height": 80.770897
      },
      "shapeId": "room-aula-430"
    },
    {
      "id": "room-aula-402",
      "label": "AULA 402",
      "aliases": [
        "aula 402",
        "402"
      ],
      "category": "aula",
      "bbox": {
        "x": 1173.105,
        "y": 398.80087,
        "width": 106.21,
        "height": 80.17131
      },
      "shapeId": "room-aula-402"
    },
    {
      "id": "room-bano-hombres",
      "label": "BAÑO HOMBRES",
      "aliases": [
        "bano hombres"
      ],
      "category": "bano",
      "bbox": {
        "x": 1110.7495,
        "y": 399.48608,
        "width": 63.040688,
        "height": 78.800858
      },
      "shapeId": "room-bano-hombres"
    },
    {
      "id": "room-aula-401",
      "label": "AULA 401",
      "aliases": [
        "aula 401",
        "401"
      ],
      "category": "aula",
      "bbox": {
        "x": 641.37048,
        "y": 398.11563,
        "width": 54.132999,
        "height": 82.226982
      },
      "shapeId": "room-aula-401"
    },
    {
      "id": "room-aula-407",
      "label": "AULA 407",
      "aliases": [
        "aula 407",
        "407"
      ],
      "category": "aula",
      "bbox": {
        "x": 695.50323,
        "y": 399.48608,
        "width": 50.706638,
        "height": 78.800858
      },
      "shapeId": "room-aula-407"
    },
    {
      "id": "room-bano-mujeres",
      "label": "BAÑO MUJERES",
      "aliases": [
        "bano mujeres"
      ],
      "category": "bano",
      "bbox": {
        "x": 746.89508,
        "y": 399.48608,
        "width": 61.669998,
        "height": 80.17131
      },
      "shapeId": "room-bano-mujeres"
    },
    {
      "id": "room-deposito-general",
      "label": "DEPÓSITO GENERAL",
      "aliases": [
        "deposito general"
      ],
      "category": "deposito",
      "bbox": {
        "x": 864.06854,
        "y": 339.87152,
        "width": 189.80701,
        "height": 121.97002
      },
      "shapeId": "room-deposito-general"
    },
    {
      "id": "room-deposito",
      "label": "DEPÓSITO",
      "aliases": [
        "deposito"
      ],
      "category": "deposito",
      "bbox": {
        "x": 1052.5054,
        "y": 109.63598,
        "width": 110.3212,
        "height": 232.29123
      },
      "shapeId": "room-deposito"
    },
    {
      "id": "room-deposito-2",
      "label": "DEPÓSITO",
      "aliases": [
        "deposito"
      ],
      "category": "deposito",
      "bbox": {
        "x": 1052.5054,
        "y": 109.63598,
        "width": 110.3212,
        "height": 232.29123
      },
      "shapeId": "room-deposito-2"
    },
    {
      "id": "room-sector-de-investigacion",
      "label": "SECTOR DE INVESTIGACIÓN",
      "aliases": [
        "sector de investigacion"
      ],
      "category": "otro",
      "bbox": {
        "x": 1166.2527,
        "y": 107.5803,
        "width": 111.00642,
        "height": 79.486084
      },
      "shapeId": "room-sector-de-investigacion"
    },
    {
      "id": "room-oficina-2",
      "label": "OFICINA",
      "aliases": [
        "oficina"
      ],
      "category": "oficina",
      "bbox": {
        "x": 606.42401,
        "y": 545.43896,
        "width": 59.271999,
        "height": 52.077087
      },
      "shapeId": "room-oficina-2"
    },
    {
      "id": "room-oficina-3",
      "label": "OFICINA",
      "aliases": [
        "oficina"
      ],
      "category": "oficina",
      "bbox": {
        "x": 605.73877,
        "y": 597.8587,
        "width": 62.013,
        "height": 48.308353
      },
      "shapeId": "room-oficina-3"
    },
    {
      "id": "room-aula-417",
      "label": "AULA 417",
      "aliases": [
        "aula 417",
        "417"
      ],
      "category": "aula",
      "bbox": {
        "x": 626.29553,
        "y": 513.2334,
        "width": 73.319,
        "height": 30.835119
      },
      "shapeId": "room-aula-417"
    },
    {
      "id": "room-sec-informat",
      "label": "SEC. INFORMÁT.",
      "aliases": [
        "sec. informat.",
        "sec informat"
      ],
      "category": "oficina",
      "bbox": {
        "x": 698.24414,
        "y": 513.2334,
        "width": 107.58,
        "height": 29.464668
      },
      "shapeId": "room-sec-informat"
    },
    {
      "id": "room-dpto-de-compu",
      "label": "DPTO. DE COMPU",
      "aliases": [
        "dpto. de compu",
        "dpto de compu"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1346.4668,
        "y": 262.44113,
        "width": 80.857002,
        "height": 96.616707
      },
      "shapeId": "room-dpto-de-compu"
    },
    {
      "id": "room-soporte-informatico",
      "label": "Soporte informático",
      "aliases": [
        "soporte informatico"
      ],
      "category": "otro",
      "bbox": {
        "x": 574.52808,
        "y": 779.84644,
        "width": 66.414001,
        "height": 74.971558
      },
      "shapeId": "room-soporte-informatico"
    }
  ]
};

export default piso4Manifest;
