// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from './types';
import type { FloorManifest } from './types';

const piso4Manifest: FloorManifest = {
  "floorId": "piso4",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-laboratorios",
      "label": "LABORATORIOS",
      "aliases": [
        "laboratorios"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 571.88025,
        "y": 166.76337,
        "width": 290.535,
        "height": 40.428265
      },
      "shapeId": "room-laboratorios"
    },
    {
      "id": "room-lab-medios-porosos",
      "label": "LAB MEDIOS POROSOS",
      "aliases": [
        "lab medios porosos"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 636.97662,
        "y": 207.19164,
        "width": 115.803,
        "height": 40.428265
      },
      "shapeId": "room-lab-medios-porosos"
    },
    {
      "id": "room-sala-lateral-superior",
      "label": "SALA LATERAL SUPERIOR",
      "aliases": [
        "sala lateral superior"
      ],
      "category": "sala",
      "bbox": {
        "x": 749.35352,
        "y": 214.04388,
        "width": 113.74732,
        "height": 183.64026
      },
      "shapeId": "room-sala-lateral-superior"
    },
    {
      "id": "room-aula-403",
      "label": "AULA 403",
      "aliases": [
        "aula 403",
        "403"
      ],
      "category": "aula",
      "bbox": {
        "x": 488.28284,
        "y": 326.42078,
        "width": 148.009,
        "height": 214.47537
      },
      "shapeId": "room-aula-403"
    },
    {
      "id": "room-aula-405",
      "label": "AULA 405",
      "aliases": [
        "aula 405",
        "405"
      ],
      "category": "aula",
      "bbox": {
        "x": 489.65329,
        "y": 544.66486,
        "width": 84.625,
        "height": 61.327625
      },
      "shapeId": "room-aula-405"
    },
    {
      "id": "room-bedelia",
      "label": "BEDELIA",
      "aliases": [
        "bedelia"
      ],
      "category": "otro",
      "bbox": {
        "x": 488.28718,
        "y": 607.1004,
        "width": 87.21484000000004,
        "height": 51.82617000000005
      },
      "shapeId": "room-bedelia"
    },
    {
      "id": "room-depto-de-ing-sanitaria",
      "label": "DEPTO DE ING SANITARIA",
      "aliases": [
        "depto de ing sanitaria"
      ],
      "category": "departamento",
      "bbox": {
        "x": 488.28718,
        "y": 652.64532,
        "width": 85.27734000000004,
        "height": 119.19335999999998
      },
      "shapeId": "room-depto-de-ing-sanitaria"
    },
    {
      "id": "room-inst-ing-biomedica",
      "label": "INST. ING. BIOMEDICA",
      "aliases": [
        "inst. ing. biomedica",
        "inst ing biomedica"
      ],
      "category": "instituto",
      "bbox": {
        "x": 488.77167,
        "y": 771.35486,
        "width": 85.277,
        "height": 69.771912
      },
      "shapeId": "room-inst-ing-biomedica"
    },
    {
      "id": "room-inst-ing-biomed",
      "label": "INST. ING. BIOMED.",
      "aliases": [
        "inst. ing. biomed.",
        "inst ing biomed"
      ],
      "category": "instituto",
      "bbox": {
        "x": 627.38348,
        "y": 771.13171,
        "width": 67.836998,
        "height": 69.20771
      },
      "shapeId": "room-inst-ing-biomed"
    },
    {
      "id": "room-aula-411",
      "label": "AULA 411",
      "aliases": [
        "aula 411",
        "411"
      ],
      "category": "aula",
      "bbox": {
        "x": 626.86188,
        "y": 707.88177,
        "width": 121.132,
        "height": 65.895691
      },
      "shapeId": "room-aula-411"
    },
    {
      "id": "room-laboratorios-2",
      "label": "LABORATORIOS",
      "aliases": [
        "laboratorios"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 695.22076,
        "y": 771.81689,
        "width": 108.266,
        "height": 63.72591
      },
      "shapeId": "room-laboratorios-2"
    },
    {
      "id": "room-ing-sanit",
      "label": "ING. SANIT.",
      "aliases": [
        "ing. sanit.",
        "ing sanit"
      ],
      "category": "otro",
      "bbox": {
        "x": 747.99371,
        "y": 706.91272,
        "width": 55.236,
        "height": 64.926636
      },
      "shapeId": "room-ing-sanit"
    },
    {
      "id": "room-aula-400",
      "label": "AULA 400",
      "aliases": [
        "aula 400",
        "400"
      ],
      "category": "aula",
      "bbox": {
        "x": 806.22717,
        "y": 738.92615,
        "width": 185.69594,
        "height": 95.93148
      },
      "shapeId": "room-aula-400"
    },
    {
      "id": "room-aula-408",
      "label": "AULA 408",
      "aliases": [
        "aula 408",
        "408"
      ],
      "category": "aula",
      "bbox": {
        "x": 991.9231,
        "y": 738.92615,
        "width": 116.48823,
        "height": 96.616707
      },
      "shapeId": "room-aula-408"
    },
    {
      "id": "room-aula-422",
      "label": "AULA 422",
      "aliases": [
        "aula 422",
        "422"
      ],
      "category": "aula",
      "bbox": {
        "x": 967.94025,
        "y": 661.49573,
        "width": 82.226997,
        "height": 47.96574
      },
      "shapeId": "room-aula-422"
    },
    {
      "id": "room-aula-416",
      "label": "AULA 416",
      "aliases": [
        "aula 416",
        "416"
      ],
      "category": "aula",
      "bbox": {
        "x": 1107.7262,
        "y": 771.81689,
        "width": 108.95075,
        "height": 65.096359
      },
      "shapeId": "room-aula-416"
    },
    {
      "id": "room-aula-414",
      "label": "AULA 414",
      "aliases": [
        "aula 414",
        "414"
      ],
      "category": "aula",
      "bbox": {
        "x": 1150.8954,
        "y": 708.091,
        "width": 128.82227,
        "height": 62.355461
      },
      "shapeId": "room-aula-414"
    },
    {
      "id": "room-aula-412",
      "label": "AULA 412",
      "aliases": [
        "aula 412",
        "412"
      ],
      "category": "aula",
      "bbox": {
        "x": 1215.9917,
        "y": 773.18738,
        "width": 63.726002,
        "height": 63.040688
      },
      "shapeId": "room-aula-412"
    },
    {
      "id": "room-dpto-naval",
      "label": "DPTO. NAVAL",
      "aliases": [
        "dpto. naval",
        "dpto naval"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1274.2358,
        "y": 839.65417,
        "width": 66.467003,
        "height": 78.115631
      },
      "shapeId": "room-dpto-naval"
    },
    {
      "id": "room-oficina",
      "label": "OFICINA",
      "aliases": [
        "oficina"
      ],
      "category": "oficina",
      "bbox": {
        "x": 1343.4435,
        "y": 784.83618,
        "width": 81.542,
        "height": 50.706638
      },
      "shapeId": "room-oficina"
    },
    {
      "id": "room-sala-pc",
      "label": "SALA PC",
      "aliases": [
        "sala pc"
      ],
      "category": "sala",
      "bbox": {
        "x": 1341.3878,
        "y": 645.73553,
        "width": 80.856529,
        "height": 139.10065
      },
      "shapeId": "room-sala-pc"
    },
    {
      "id": "room-sala-pc-2",
      "label": "SALA PC",
      "aliases": [
        "sala pc"
      ],
      "category": "sala",
      "bbox": {
        "x": 1341.3878,
        "y": 645.73553,
        "width": 80.856529,
        "height": 139.10065
      },
      "shapeId": "room-sala-pc-2"
    },
    {
      "id": "room-servicio-de-computacion",
      "label": "Servicio de computación",
      "aliases": [
        "servicio de computacion"
      ],
      "category": "otro",
      "bbox": {
        "x": 1341.3878,
        "y": 537.47003,
        "width": 82.912003,
        "height": 108.26553
      },
      "shapeId": "room-servicio-de-computacion"
    },
    {
      "id": "room-comunicacion-e-intercambios-academ",
      "label": "COMUNICACIÓN E INTERCAMBIOS ACADÉM.",
      "aliases": [
        "comunicacion e intercambios academ.",
        "comunicacion e intercambios academ"
      ],
      "category": "otro",
      "bbox": {
        "x": 1049.4821,
        "y": 576.52783,
        "width": 260.38501,
        "height": 26.72377
      },
      "shapeId": "room-comunicacion-e-intercambios-academ"
    },
    {
      "id": "room-sala-del-mainframe",
      "label": "SALA DEL MAINFRAME",
      "aliases": [
        "sala del mainframe"
      ],
      "category": "sala",
      "bbox": {
        "x": 1342.0731,
        "y": 418.24091,
        "width": 84.282654,
        "height": 119.91435
      },
      "shapeId": "room-sala-del-mainframe"
    },
    {
      "id": "room-aula-430",
      "label": "AULA 430",
      "aliases": [
        "aula 430",
        "430"
      ],
      "category": "aula",
      "bbox": {
        "x": 1273.7219,
        "y": 462.86615,
        "width": 5.7981277,
        "height": 80.770897
      },
      "shapeId": "room-aula-430"
    },
    {
      "id": "room-aula-402",
      "label": "AULA 402",
      "aliases": [
        "aula 402",
        "402"
      ],
      "category": "aula",
      "bbox": {
        "x": 1170.0817,
        "y": 459.3544,
        "width": 106.21,
        "height": 80.17131
      },
      "shapeId": "room-aula-402"
    },
    {
      "id": "room-bano-hombres",
      "label": "BAÑO HOMBRES",
      "aliases": [
        "bano hombres"
      ],
      "category": "bano",
      "bbox": {
        "x": 1107.7262,
        "y": 460.03961,
        "width": 63.040688,
        "height": 78.800858
      },
      "shapeId": "room-bano-hombres"
    },
    {
      "id": "room-aula-401",
      "label": "AULA 401",
      "aliases": [
        "aula 401",
        "401"
      ],
      "category": "aula",
      "bbox": {
        "x": 638.34711,
        "y": 458.66916,
        "width": 54.132999,
        "height": 82.226982
      },
      "shapeId": "room-aula-401"
    },
    {
      "id": "room-aula-407",
      "label": "AULA 407",
      "aliases": [
        "aula 407",
        "407"
      ],
      "category": "aula",
      "bbox": {
        "x": 692.47986,
        "y": 460.03961,
        "width": 50.706638,
        "height": 78.800858
      },
      "shapeId": "room-aula-407"
    },
    {
      "id": "room-bano-mujeres",
      "label": "BAÑO MUJERES",
      "aliases": [
        "bano mujeres"
      ],
      "category": "bano",
      "bbox": {
        "x": 743.8717,
        "y": 460.03961,
        "width": 61.669998,
        "height": 80.17131
      },
      "shapeId": "room-bano-mujeres"
    },
    {
      "id": "room-deposito-general",
      "label": "DEPÓSITO GENERAL",
      "aliases": [
        "deposito general"
      ],
      "category": "deposito",
      "bbox": {
        "x": 861.04517,
        "y": 400.42505,
        "width": 189.80701,
        "height": 121.97002
      },
      "shapeId": "room-deposito-general"
    },
    {
      "id": "room-deposito",
      "label": "DEPÓSITO",
      "aliases": [
        "deposito"
      ],
      "category": "deposito",
      "bbox": {
        "x": 1049.4821,
        "y": 170.1895,
        "width": 110.3212,
        "height": 232.29123
      },
      "shapeId": "room-deposito"
    },
    {
      "id": "room-deposito-2",
      "label": "DEPÓSITO",
      "aliases": [
        "deposito"
      ],
      "category": "deposito",
      "bbox": {
        "x": 1049.4821,
        "y": 170.1895,
        "width": 110.3212,
        "height": 232.29123
      },
      "shapeId": "room-deposito-2"
    },
    {
      "id": "room-sector-de-investigacion",
      "label": "SECTOR DE INVESTIGACIÓN",
      "aliases": [
        "sector de investigacion"
      ],
      "category": "otro",
      "bbox": {
        "x": 1163.2294,
        "y": 168.13382,
        "width": 111.00642,
        "height": 79.486084
      },
      "shapeId": "room-sector-de-investigacion"
    },
    {
      "id": "room-oficina-2",
      "label": "OFICINA",
      "aliases": [
        "oficina"
      ],
      "category": "oficina",
      "bbox": {
        "x": 603.40063,
        "y": 605.99249,
        "width": 59.271999,
        "height": 52.077087
      },
      "shapeId": "room-oficina-2"
    },
    {
      "id": "room-oficina-3",
      "label": "OFICINA",
      "aliases": [
        "oficina"
      ],
      "category": "oficina",
      "bbox": {
        "x": 602.71539,
        "y": 658.41223,
        "width": 62.013,
        "height": 48.308353
      },
      "shapeId": "room-oficina-3"
    },
    {
      "id": "room-aula-417",
      "label": "AULA 417",
      "aliases": [
        "aula 417",
        "417"
      ],
      "category": "aula",
      "bbox": {
        "x": 623.27216,
        "y": 573.78693,
        "width": 73.319,
        "height": 30.835119
      },
      "shapeId": "room-aula-417"
    },
    {
      "id": "room-sec-informat",
      "label": "SEC. INFORMÁT.",
      "aliases": [
        "sec. informat.",
        "sec informat"
      ],
      "category": "oficina",
      "bbox": {
        "x": 695.22076,
        "y": 573.78693,
        "width": 107.58,
        "height": 29.464668
      },
      "shapeId": "room-sec-informat"
    },
    {
      "id": "room-dpto-de-compu",
      "label": "DPTO. DE COMPU",
      "aliases": [
        "dpto. de compu",
        "dpto de compu"
      ],
      "category": "departamento",
      "bbox": {
        "x": 425.9278,
        "y": 162.30352,
        "width": 1063.4687,
        "height": 759.73828
      },
      "shapeId": "room-dpto-de-compu"
    },
    {
      "id": "room-soporte-informatico",
      "label": "Soporte informático",
      "aliases": [
        "soporte informatico"
      ],
      "category": "otro",
      "bbox": {
        "x": 571.5047,
        "y": 840.39996,
        "width": 66.414001,
        "height": 74.971558
      },
      "shapeId": "room-soporte-informatico"
    }
  ]
};

export default piso4Manifest;
