// AUTO-GENERATED by scripts/build_floor_manifest.js — do not edit manually
export type { RoomCategory, Room, FloorManifest } from './types';
import type { FloorManifest } from './types';

const subsuelo1Manifest: FloorManifest = {
  "floorId": "subsuelo1",
  "viewBox": [
    0,
    0,
    1920,
    1080
  ],
  "rooms": [
    {
      "id": "room-taller-de-mecanica-de-ensenanza",
      "label": "TALLER DE MECÁNICA DE ENSEÑANZA",
      "aliases": [
        "taller de mecanica de ensenanza"
      ],
      "category": "otro",
      "bbox": {
        "x": 761.02838,
        "y": 98.668434,
        "width": 224.66516,
        "height": 86.849129
      },
      "shapeId": "room-taller-de-mecanica-de-ensenanza"
    },
    {
      "id": "room-aula-e32",
      "label": "AULA E32",
      "aliases": [
        "aula e32"
      ],
      "category": "aula",
      "bbox": {
        "x": 1072.2367,
        "y": 189.19899,
        "width": 79.428436,
        "height": 121.45364
      },
      "shapeId": "room-aula-e32"
    },
    {
      "id": "room-aula-e33",
      "label": "AULA E33",
      "aliases": [
        "aula e33"
      ],
      "category": "aula",
      "bbox": {
        "x": 1099.4495,
        "y": 98.534271,
        "width": 54.31353,
        "height": 85.534126
      },
      "shapeId": "room-aula-e33"
    },
    {
      "id": "room-comedor",
      "label": "COMEDOR",
      "aliases": [
        "comedor"
      ],
      "category": "otro",
      "bbox": {
        "x": 1340.546,
        "y": 264.3913,
        "width": 159.49272,
        "height": 230.32227
      },
      "shapeId": "room-comedor"
    },
    {
      "id": "room-comedor-docente",
      "label": "COMEDOR DOCENTE",
      "aliases": [
        "comedor docente"
      ],
      "category": "otro",
      "bbox": {
        "x": 1414.2919,
        "y": 493.78775,
        "width": 83.464996,
        "height": 57.618923
      },
      "shapeId": "room-comedor-docente"
    },
    {
      "id": "room-aula-e14",
      "label": "AULA E14",
      "aliases": [
        "aula e14"
      ],
      "category": "aula",
      "bbox": {
        "x": 1226.1163,
        "y": 494.81088,
        "width": 96.487953,
        "height": 68.06778
      },
      "shapeId": "room-aula-e14"
    },
    {
      "id": "room-aula-e16",
      "label": "AULA E16",
      "aliases": [
        "aula e16"
      ],
      "category": "aula",
      "bbox": {
        "x": 1218.561,
        "y": 409.62891,
        "width": 120.98738,
        "height": 86.272606
      },
      "shapeId": "room-aula-e16"
    },
    {
      "id": "room-depto-mecanica-aplicada",
      "label": "DEPTO. MECÁNICA APLICADA",
      "aliases": [
        "depto. mecanica aplicada",
        "depto mecanica aplicada"
      ],
      "category": "departamento",
      "bbox": {
        "x": 1022.1707,
        "y": 347.15692,
        "width": 191.12402,
        "height": 57.401463
      },
      "shapeId": "room-depto-mecanica-aplicada"
    },
    {
      "id": "room-oficinas-de-lab-de-fluido-dinamico",
      "label": "OFICINAS DE LAB. DE FLUIDO-DINÁMICO",
      "aliases": [
        "oficinas de lab. de fluido-dinamico",
        "oficinas de lab de fluido-dinamico"
      ],
      "category": "oficina",
      "bbox": {
        "x": 793.45813,
        "y": 352.1041,
        "width": 178.52199,
        "height": 57.446339
      },
      "shapeId": "room-oficinas-de-lab-de-fluido-dinamico"
    },
    {
      "id": "room-lab-solidos-amorfos",
      "label": "LAB.SOLIDOS AMORFOS",
      "aliases": [
        "lab.solidos amorfos",
        "labsolidos amorfos"
      ],
      "category": "laboratorio",
      "bbox": {
        "x": 494.3024,
        "y": 265.38614,
        "width": 84.560616,
        "height": 47.597622
      },
      "shapeId": "room-lab-solidos-amorfos"
    },
    {
      "id": "room-oficina-sol-amor",
      "label": "OFICINA SOL. AMOR.",
      "aliases": [
        "oficina sol. amor.",
        "oficina sol amor"
      ],
      "category": "oficina",
      "bbox": {
        "x": 526.07349,
        "y": 314.55423,
        "width": 64.590378,
        "height": 56.770428
      },
      "shapeId": "room-oficina-sol-amor"
    },
    {
      "id": "room-aula-e29",
      "label": "AULA E29",
      "aliases": [
        "aula e29"
      ],
      "category": "aula",
      "bbox": {
        "x": 582.96497,
        "y": 495.90039,
        "width": 90.754257,
        "height": 94.753487
      },
      "shapeId": "room-aula-e29"
    },
    {
      "id": "room-aula-e7",
      "label": "AULA E7",
      "aliases": [
        "aula e7"
      ],
      "category": "aula",
      "bbox": {
        "x": 582.9494,
        "y": 591.59424,
        "width": 89.010643,
        "height": 83.475533
      },
      "shapeId": "room-aula-e7"
    },
    {
      "id": "room-aula-e5",
      "label": "AULA E5",
      "aliases": [
        "aula e5"
      ],
      "category": "aula",
      "bbox": {
        "x": 497.09314,
        "y": 628.88635,
        "width": 81.963852,
        "height": 84.940231
      },
      "shapeId": "room-aula-e5"
    },
    {
      "id": "room-aula-e3",
      "label": "AULA E3",
      "aliases": [
        "aula e3"
      ],
      "category": "aula",
      "bbox": {
        "x": 495.80432,
        "y": 717.10724,
        "width": 82.588547,
        "height": 97.567207
      },
      "shapeId": "room-aula-e3"
    },
    {
      "id": "room-aula-e1",
      "label": "AULA E1",
      "aliases": [
        "aula e1"
      ],
      "category": "aula",
      "bbox": {
        "x": 584.18677,
        "y": 819.24103,
        "width": 68.382019,
        "height": 82.198929
      },
      "shapeId": "room-aula-e1"
    },
    {
      "id": "room-jardin-maternal",
      "label": "JARDÍN MATERNAL",
      "aliases": [
        "jardin maternal"
      ],
      "category": "otro",
      "bbox": {
        "x": 645.05841,
        "y": 407.68619,
        "width": 117.30956,
        "height": 26.411133
      },
      "shapeId": "room-jardin-maternal"
    },
    {
      "id": "room-aula-e8",
      "label": "AULA E8",
      "aliases": [
        "aula e8"
      ],
      "category": "aula",
      "bbox": {
        "x": 1315.1306,
        "y": 656.83289,
        "width": 92.075363,
        "height": 90.429413
      },
      "shapeId": "room-aula-e8"
    },
    {
      "id": "room-aula-e10",
      "label": "AULA E10",
      "aliases": [
        "aula e10"
      ],
      "category": "aula",
      "bbox": {
        "x": 1300.0737,
        "y": 567.74353,
        "width": 75.228386,
        "height": 88.485191
      },
      "shapeId": "room-aula-e10"
    },
    {
      "id": "room-gab-e11",
      "label": "GAB. E11",
      "aliases": [
        "gab. e11",
        "gab e11"
      ],
      "category": "otro",
      "bbox": {
        "x": 1158.9663,
        "y": 675.94843,
        "width": 58.741425,
        "height": 50.699509
      },
      "shapeId": "room-gab-e11"
    },
    {
      "id": "room-aula-e9",
      "label": "AULA E9",
      "aliases": [
        "aula e9"
      ],
      "category": "aula",
      "bbox": {
        "x": 613.62903,
        "y": 676.66089,
        "width": 153.15375,
        "height": 68.309151
      },
      "shapeId": "room-aula-e9"
    },
    {
      "id": "room-sala-de-compu",
      "label": "SALA DE COMPU",
      "aliases": [
        "sala de compu"
      ],
      "category": "sala",
      "bbox": {
        "x": 1271.5647,
        "y": 749.92401,
        "width": 70.197647,
        "height": 69.950722
      },
      "shapeId": "room-sala-de-compu"
    }
  ]
};

export default subsuelo1Manifest;
